server:
  port: 80

spring:
  profiles:
    include: oauth
  application:
    name: genie
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cluv-2.cdvey5izwfml.ap-northeast-2.rds.amazonaws.com:3306/it1870??useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: it1870
    password: it1870

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace